window.VM_TRANSLATIONS = {
  en: {
    navStay:'Stay', navExperiences:'Experiences', navGallery:'Gallery', navJourney:'Getting here', planStay:'Plan your stay',
    location:'Inhaca Island · Mozambique', heroTitle:'Trade the city<br>for island time.', heroLede:'Ten peaceful rooms, breakfast each morning and the Indian Ocean on your doorstep — only a 60-minute speedboat ride from Maputo.', checkDates:'Check your dates', discover:'Discover Villa Martins', guestRooms:'guest rooms', fromMaputo:'from Maputo', daily:'Daily', breakfastIncluded:'breakfast included',
    storyEyebrow:'The island, at your pace', storyTitle:'A quieter kind of luxury.', storyLead:'Here, luxury is the freedom to slow down: a warm welcome, a barefoot walk to the shore, and nowhere else you need to be.', storyBody:'Villa Martins was created as a comfortable, authentic island retreat. Spaces are relaxed and welcoming, with nature always close — from the palms and ocean breeze to the spectacular marine reserve nearby.', welcomeHome:'Welcome to your island home',
    stayEyebrow:'Stay well', stayTitle:'Simple. Comfortable.<br>Made for switching off.', stayBody:'Ten thoughtfully designed rooms open onto tropical gardens and the pool. Each stay includes daily breakfast, with a restaurant available for other meals.', villaKicker:'The Villa', villaTitle:'Everything close, nothing rushed.', poolGarden:'Pool & garden', restaurant:'Restaurant on site', poolsideKicker:'Poolside days', poolsideTitle:'Cool water, warm sun.', quote:'“A peaceful piece of paradise.”',
    experiencesEyebrow:'Out on the island', experiencesTitle:'Follow the tide.', experiencesBody:'Spend the day in clear water, discover quiet beaches or see the island from above. We can help shape the day around you.', snorkelling:'Snorkelling', snorkellingBody:'Meet vibrant marine life in clear, warm water.', beachWalks:'Beach walks', beachWalksBody:'Barefoot strolls and quiet moments by the shore.', islandTour:'Island tour', islandTourBody:'Explore Inhaca and climb to the historic lighthouse.', fishing:'Ocean fishing', fishingShort:'Fishing', fishingBody:"Head offshore into the Indian Ocean's rich waters.", whales:'Whale watching', whalesBody:'Witness humpback migration in season.',
    galleryEyebrow:'A glimpse of island life', galleryTitle:'Wish you were here?', galleryBody:'Slow mornings, blue water and golden-hour dinners. Tap any photograph for a closer look.', galleryCount:'Complete gallery · 27 photographs',
    journeyEyebrow:'The journey is part of it', journeyTitle:'Maputo to island calm in 60 minutes.', journeyBody:'Our speedboat transfer connects Maputo and Inhaca Island, turning your arrival into the first memorable part of the escape.', routeMeet:'Meet in Maputo', routeMeetBody:'We confirm your departure details.', routeCross:'Cross the bay', routeCrossBody:'A scenic 60-minute speedboat ride.', routeArrive:'Arrive on Inhaca', routeArriveBody:'Welcome to Villa Martins.', viewMap:'View on Google Maps',
    ctaEyebrow:'Your island dates', ctaTitle:'Ready when you are.', ctaBody:'Tell us when you would like to travel and what your perfect island stay looks like. Our team will confirm availability and tailor the details.', startReservation:'Start your reservation', noPayment:'No payment required · Request by WhatsApp or email',
    bookingEyebrow:'Reservation request', bookingTitle:'Let’s plan your island stay.', bookingBody:'Share a few details and choose how to send your request. The Villa Martins team will reply with availability and a tailored quotation.', name:'Name and surname', arrival:'Arrival', departure:'Departure', adults:'Adults', children:'Children (4–12)', addStay:'Add to your stay', boatTransfer:'Return boat transfer', anythingElse:'Anything else?', messagePlaceholder:'Celebration, dietary needs, room preference…', summaryPrompt:'Choose your dates to see your stay summary.', sendWhatsApp:'Send via WhatsApp', sendEmail:'Send by email', errorDate:'Please choose a departure date after your arrival.', night:'night', nights:'nights', adultWord:'adult', adultsWord:'adults', childWord:'child', childrenWord:'children', reservations:'Reservations', follow:'Follow'
  },
  pt: {
    navStay:'Estadia', navExperiences:'Experiências', navGallery:'Galeria', navJourney:'Como chegar', planStay:'Planeie a sua estadia',
    location:'Ilha da Inhaca · Moçambique', heroTitle:'Troque a cidade<br>pelo ritmo da ilha.', heroLede:'Dez quartos tranquilos, pequeno-almoço todas as manhãs e o Oceano Índico à sua porta — a apenas 60 minutos de Maputo de lancha.', checkDates:'Ver datas', discover:'Descobrir Villa Martins', guestRooms:'quartos', fromMaputo:'desde Maputo', daily:'Diário', breakfastIncluded:'pequeno-almoço incluído',
    storyEyebrow:'A ilha, ao seu ritmo', storyTitle:'Um luxo mais sereno.', storyLead:'Aqui, luxo é ter liberdade para abrandar: uma receção calorosa, uma caminhada descalça até à praia e nenhum outro lugar onde precise de estar.', storyBody:'A Villa Martins foi criada como um refúgio confortável e autêntico. Os espaços são descontraídos e acolhedores, sempre ligados à natureza, das palmeiras e brisa do mar à espetacular reserva marinha.', welcomeHome:'Bem-vindo à sua casa na ilha',
    stayEyebrow:'Descanse bem', stayTitle:'Simples. Confortável.<br>Feito para desligar.', stayBody:'Dez quartos pensados para o conforto abrem-se para jardins tropicais e para a piscina. Cada estadia inclui pequeno-almoço diário e o restaurante serve as restantes refeições.', villaKicker:'A Villa', villaTitle:'Tudo perto, nada apressado.', poolGarden:'Piscina e jardim', restaurant:'Restaurante no local', poolsideKicker:'Dias junto à piscina', poolsideTitle:'Água fresca, sol quente.', quote:'“Um pedaço tranquilo do paraíso.”',
    experiencesEyebrow:'Pela ilha', experiencesTitle:'Siga a maré.', experiencesBody:'Passe o dia em águas cristalinas, descubra praias tranquilas ou veja a ilha do alto. Ajudamos a criar o dia ao seu ritmo.', snorkelling:'Snorkelling', snorkellingBody:'Descubra vida marinha vibrante em águas claras e quentes.', beachWalks:'Passeios na praia', beachWalksBody:'Caminhadas descalças e momentos tranquilos junto ao mar.', islandTour:'Passeio pela ilha', islandTourBody:'Explore a Inhaca e suba ao farol histórico.', fishing:'Pesca oceânica', fishingShort:'Pesca', fishingBody:'Aventure-se nas águas ricas do Oceano Índico.', whales:'Observação de baleias', whalesBody:'Veja a migração das baleias-jubarte na época certa.',
    galleryEyebrow:'Um pouco da vida na ilha', galleryTitle:'Gostava de estar aqui?', galleryBody:'Manhãs lentas, água azul e jantares ao pôr do sol. Toque numa fotografia para ver melhor.', galleryCount:'Galeria completa · 27 fotografias',
    journeyEyebrow:'A viagem também faz parte', journeyTitle:'De Maputo à calma da ilha em 60 minutos.', journeyBody:'A nossa lancha liga Maputo à Ilha da Inhaca, transformando a chegada no primeiro momento memorável da escapadinha.', routeMeet:'Encontro em Maputo', routeMeetBody:'Confirmamos os detalhes da partida.', routeCross:'Travessia da baía', routeCrossBody:'Uma viagem panorâmica de 60 minutos.', routeArrive:'Chegada à Inhaca', routeArriveBody:'Bem-vindo à Villa Martins.', viewMap:'Ver no Google Maps',
    ctaEyebrow:'As suas datas na ilha', ctaTitle:'Quando quiser.', ctaBody:'Diga-nos quando gostaria de viajar e como imagina a sua estadia perfeita. A nossa equipa confirmará a disponibilidade e preparará os detalhes.', startReservation:'Iniciar reserva', noPayment:'Sem pagamento · Pedido por WhatsApp ou email',
    bookingEyebrow:'Pedido de reserva', bookingTitle:'Vamos planear a sua estadia.', bookingBody:'Partilhe alguns detalhes e escolha como enviar o pedido. A equipa da Villa Martins responderá com disponibilidade e uma proposta personalizada.', name:'Nome e apelido', arrival:'Chegada', departure:'Partida', adults:'Adultos', children:'Crianças (4–12)', addStay:'Adicionar à estadia', boatTransfer:'Transfer de barco ida e volta', anythingElse:'Mais alguma coisa?', messagePlaceholder:'Celebração, alimentação, preferência de quarto…', summaryPrompt:'Escolha as datas para ver o resumo da estadia.', sendWhatsApp:'Enviar por WhatsApp', sendEmail:'Enviar por email', errorDate:'Escolha uma data de partida posterior à chegada.', night:'noite', nights:'noites', adultWord:'adulto', adultsWord:'adultos', childWord:'criança', childrenWord:'crianças', reservations:'Reservas', follow:'Siga-nos'
  },
  fr: {
    navStay:'Séjour', navExperiences:'Expériences', navGallery:'Galerie', navJourney:'Venir', planStay:'Planifier le séjour',
    location:'Île d’Inhaca · Mozambique', heroTitle:'Quittez la ville<br>pour le rythme de l’île.', heroLede:'Dix chambres paisibles, le petit-déjeuner chaque matin et l’océan Indien à votre porte — à seulement 60 minutes de Maputo en bateau rapide.', checkDates:'Voir les dates', discover:'Découvrir Villa Martins', guestRooms:'chambres', fromMaputo:'depuis Maputo', daily:'Chaque jour', breakfastIncluded:'petit-déjeuner inclus',
    storyEyebrow:'L’île, à votre rythme', storyTitle:'Un luxe tout en douceur.', storyLead:'Ici, le luxe est la liberté de ralentir : un accueil chaleureux, une marche pieds nus vers la plage et nulle part ailleurs où vous devez être.', storyBody:'Villa Martins a été pensée comme un refuge insulaire confortable et authentique. Les espaces sont simples et accueillants, toujours proches de la nature, des palmiers à la réserve marine voisine.', welcomeHome:'Bienvenue dans votre maison sur l’île',
    stayEyebrow:'Séjournez sereinement', stayTitle:'Simple. Confortable.<br>Fait pour déconnecter.', stayBody:'Dix chambres soignées s’ouvrent sur les jardins tropicaux et la piscine. Chaque séjour comprend le petit-déjeuner, avec un restaurant pour les autres repas.', villaKicker:'La Villa', villaTitle:'Tout est proche, rien ne presse.', poolGarden:'Piscine et jardin', restaurant:'Restaurant sur place', poolsideKicker:'Journées piscine', poolsideTitle:'Eau fraîche, soleil chaud.', quote:'« Un paisible coin de paradis. »',
    experiencesEyebrow:'Sur l’île', experiencesTitle:'Suivez la marée.', experiencesBody:'Passez la journée dans une eau claire, découvrez des plages tranquilles ou admirez l’île d’en haut. Nous composons la journée avec vous.', snorkelling:'Snorkeling', snorkellingBody:'Découvrez une vie marine éclatante dans une eau claire et chaude.', beachWalks:'Balades sur la plage', beachWalksBody:'Marches pieds nus et moments calmes au bord de l’eau.', islandTour:'Tour de l’île', islandTourBody:'Explorez Inhaca et montez au phare historique.', fishing:'Pêche en mer', fishingShort:'Pêche', fishingBody:'Partez au large dans les eaux riches de l’océan Indien.', whales:'Observation des baleines', whalesBody:'Admirez la migration des baleines à bosse en saison.',
    galleryEyebrow:'Un aperçu de la vie insulaire', galleryTitle:'Vous aimeriez être ici ?', galleryBody:'Matins tranquilles, eau bleue et dîners au coucher du soleil. Touchez une photo pour l’agrandir.', galleryCount:'Galerie complète · 27 photos',
    journeyEyebrow:'Le voyage fait partie de l’expérience', journeyTitle:'De Maputo au calme de l’île en 60 minutes.', journeyBody:'Notre bateau rapide relie Maputo à Inhaca et transforme votre arrivée en premier souvenir du séjour.', routeMeet:'Rendez-vous à Maputo', routeMeetBody:'Nous confirmons les détails du départ.', routeCross:'Traversée de la baie', routeCrossBody:'60 minutes de voyage panoramique.', routeArrive:'Arrivée à Inhaca', routeArriveBody:'Bienvenue à Villa Martins.', viewMap:'Voir sur Google Maps',
    ctaEyebrow:'Vos dates sur l’île', ctaTitle:'Quand vous êtes prêt.', ctaBody:'Dites-nous quand vous souhaitez voyager et à quoi ressemble votre séjour idéal. Notre équipe confirmera les disponibilités et personnalisera les détails.', startReservation:'Commencer la réservation', noPayment:'Aucun paiement · Demande par WhatsApp ou e-mail',
    bookingEyebrow:'Demande de réservation', bookingTitle:'Planifions votre séjour.', bookingBody:'Partagez quelques détails et choisissez comment envoyer la demande. L’équipe répondra avec les disponibilités et un devis personnalisé.', name:'Nom et prénom', arrival:'Arrivée', departure:'Départ', adults:'Adultes', children:'Enfants (4–12)', addStay:'Ajouter au séjour', boatTransfer:'Transfert bateau aller-retour', anythingElse:'Autre chose ?', messagePlaceholder:'Célébration, alimentation, préférence de chambre…', summaryPrompt:'Choisissez vos dates pour voir le résumé.', sendWhatsApp:'Envoyer par WhatsApp', sendEmail:'Envoyer par e-mail', errorDate:'Choisissez une date de départ après l’arrivée.', night:'nuit', nights:'nuits', adultWord:'adulte', adultsWord:'adultes', childWord:'enfant', childrenWord:'enfants', reservations:'Réservations', follow:'Suivre'
  },
  af: {
    navStay:'Verblyf', navExperiences:'Ervarings', navGallery:'Galery', navJourney:'Hoe om hier te kom', planStay:'Beplan jou verblyf',
    location:'Inhaca-eiland · Mosambiek', heroTitle:'Ruil die stad<br>vir eilandtyd.', heroLede:'Tien rustige kamers, ontbyt elke oggend en die Indiese Oseaan op jou voorstoep — net 60 minute per snelboot vanaf Maputo.', checkDates:'Kyk na datums', discover:'Ontdek Villa Martins', guestRooms:'gastekamers', fromMaputo:'vanaf Maputo', daily:'Daagliks', breakfastIncluded:'ontbyt ingesluit',
    storyEyebrow:'Die eiland, op jou tempo', storyTitle:'’n Rustiger soort luuksheid.', storyLead:'Hier is luuksheid die vryheid om stadiger te leef: ’n warm verwelkoming, kaalvoet na die strand en nêrens anders waar jy hoef te wees nie.', storyBody:'Villa Martins is geskep as ’n gemaklike, egte eiland-toevlug. Die ruimtes is ontspanne en verwelkomend, altyd naby aan die natuur en die merkwaardige mariene reservaat.', welcomeHome:'Welkom by jou eilandtuiste',
    stayEyebrow:'Bly lekker', stayTitle:'Eenvoudig. Gemaklik.<br>Gemaak om af te skakel.', stayBody:'Tien sorgvuldig ontwerpte kamers kyk uit oor tropiese tuine en die swembad. Daaglikse ontbyt is ingesluit, met ’n restaurant vir ander etes.', villaKicker:'Die Villa', villaTitle:'Alles naby, niks gejaag nie.', poolGarden:'Swembad en tuin', restaurant:'Restaurant op die perseel', poolsideKicker:'Dae langs die swembad', poolsideTitle:'Koel water, warm son.', quote:'“’n Rustige stukkie paradys.”',
    experiencesEyebrow:'Op die eiland', experiencesTitle:'Volg die gety.', experiencesBody:'Bring die dag in helder water deur, ontdek stil strande of sien die eiland van bo. Ons help om die dag rondom jou te vorm.', snorkelling:'Snorkel', snorkellingBody:'Ontdek kleurvolle seelewe in helder, warm water.', beachWalks:'Strandstappe', beachWalksBody:'Kaalvoetstappe en stil oomblikke langs die kus.', islandTour:'Eilandtoer', islandTourBody:'Verken Inhaca en klim na die historiese vuurtoring.', fishing:'Oseaanhengel', fishingShort:'Hengel', fishingBody:'Vaar uit na die ryk waters van die Indiese Oseaan.', whales:'Walviskyk', whalesBody:'Sien boggelrugwalvisse tydens hul seisoenale migrasie.',
    galleryEyebrow:'’n Kykie na eilandlewe', galleryTitle:'Wens jy was hier?', galleryBody:'Stadige oggende, blou water en aandetes teen sononder. Tik op enige foto vir ’n nader kyk.', galleryCount:'Volledige galery · 27 foto’s',
    journeyEyebrow:'Die reis is deel daarvan', journeyTitle:'Van Maputo na eilandrus in 60 minute.', journeyBody:'Ons snelboot verbind Maputo en Inhaca-eiland en maak jou aankoms die eerste onvergeetlike deel van die wegbreek.', routeMeet:'Ontmoet in Maputo', routeMeetBody:'Ons bevestig jou vertrekbesonderhede.', routeCross:'Steek die baai oor', routeCrossBody:'’n Skilderagtige rit van 60 minute.', routeArrive:'Arriveer op Inhaca', routeArriveBody:'Welkom by Villa Martins.', viewMap:'Sien op Google Maps',
    ctaEyebrow:'Jou eilanddatums', ctaTitle:'Wanneer jy gereed is.', ctaBody:'Vertel ons wanneer jy wil reis en hoe jou ideale eilandverblyf lyk. Ons span bevestig beskikbaarheid en pas die besonderhede aan.', startReservation:'Begin jou bespreking', noPayment:'Geen betaling nodig · Versoek via WhatsApp of e-pos',
    bookingEyebrow:'Besprekingsversoek', bookingTitle:'Kom ons beplan jou eilandverblyf.', bookingBody:'Deel ’n paar besonderhede en kies hoe om die versoek te stuur. Die span antwoord met beskikbaarheid en ’n persoonlike kwotasie.', name:'Naam en van', arrival:'Aankoms', departure:'Vertrek', adults:'Volwassenes', children:'Kinders (4–12)', addStay:'Voeg by jou verblyf', boatTransfer:'Heen-en-weer bootvervoer', anythingElse:'Enigiets anders?', messagePlaceholder:'Viering, dieetbehoeftes, kamervoorkeur…', summaryPrompt:'Kies jou datums om die opsomming te sien.', sendWhatsApp:'Stuur via WhatsApp', sendEmail:'Stuur per e-pos', errorDate:'Kies ’n vertrekdatum ná jou aankoms.', night:'nag', nights:'nagte', adultWord:'volwassene', adultsWord:'volwassenes', childWord:'kind', childrenWord:'kinders', reservations:'Besprekings', follow:'Volg ons'
  },
  nl: {
    navStay:'Verblijf', navExperiences:'Ervaringen', navGallery:'Galerij', navJourney:'Route', planStay:'Plan je verblijf',
    location:'Inhaca-eiland · Mozambique', heroTitle:'Ruil de stad<br>in voor eilandtijd.', heroLede:'Tien rustige kamers, elke ochtend ontbijt en de Indische Oceaan voor de deur — op slechts 60 minuten per speedboot van Maputo.', checkDates:'Bekijk data', discover:'Ontdek Villa Martins', guestRooms:'gastenkamers', fromMaputo:'vanaf Maputo', daily:'Dagelijks', breakfastIncluded:'ontbijt inbegrepen',
    storyEyebrow:'Het eiland, op jouw tempo', storyTitle:'Een rustiger soort luxe.', storyLead:'Hier is luxe de vrijheid om te vertragen: een warm welkom, blootsvoets naar het strand en nergens anders hoeven zijn.', storyBody:'Villa Martins is ontworpen als een comfortabel, authentiek eilandverblijf. De ruimtes zijn ontspannen en gastvrij, altijd verbonden met de natuur en het nabijgelegen zeereservaat.', welcomeHome:'Welkom in je eilandhuis',
    stayEyebrow:'Heerlijk verblijven', stayTitle:'Eenvoudig. Comfortabel.<br>Gemaakt om los te laten.', stayBody:'Tien zorgvuldig ingerichte kamers grenzen aan tropische tuinen en het zwembad. Dagelijks ontbijt is inbegrepen en het restaurant verzorgt andere maaltijden.', villaKicker:'De Villa', villaTitle:'Alles dichtbij, niets gehaast.', poolGarden:'Zwembad en tuin', restaurant:'Restaurant ter plaatse', poolsideKicker:'Dagen aan het zwembad', poolsideTitle:'Koel water, warme zon.', quote:'“Een rustig stukje paradijs.”',
    experiencesEyebrow:'Op het eiland', experiencesTitle:'Volg het getij.', experiencesBody:'Breng de dag door in helder water, ontdek stille stranden of bekijk het eiland van boven. Wij helpen de dag op jouw manier in te vullen.', snorkelling:'Snorkelen', snorkellingBody:'Ontdek kleurrijk zeeleven in helder, warm water.', beachWalks:'Strandwandelingen', beachWalksBody:'Blootsvoetse wandelingen en rustige momenten aan zee.', islandTour:'Eilandtour', islandTourBody:'Verken Inhaca en beklim de historische vuurtoren.', fishing:'Zeevissen', fishingShort:'Vissen', fishingBody:'Vaar uit naar de rijke wateren van de Indische Oceaan.', whales:'Walvissen kijken', whalesBody:'Zie de seizoensmigratie van bultruggen.',
    galleryEyebrow:'Een kijkje in het eilandleven', galleryTitle:'Was je maar hier?', galleryBody:'Langzame ochtenden, blauw water en diners bij zonsondergang. Tik op een foto om deze te vergroten.', galleryCount:'Volledige galerij · 27 foto’s',
    journeyEyebrow:'De reis hoort erbij', journeyTitle:'Van Maputo naar eilandrust in 60 minuten.', journeyBody:'Onze speedboot verbindt Maputo en Inhaca en maakt van de aankomst het eerste bijzondere moment van je verblijf.', routeMeet:'Ontmoet in Maputo', routeMeetBody:'We bevestigen de vertrekgegevens.', routeCross:'Steek de baai over', routeCrossBody:'Een schilderachtige boottocht van 60 minuten.', routeArrive:'Aankomst op Inhaca', routeArriveBody:'Welkom bij Villa Martins.', viewMap:'Bekijk op Google Maps',
    ctaEyebrow:'Jouw eilanddata', ctaTitle:'Wanneer jij klaar bent.', ctaBody:'Vertel ons wanneer je wilt reizen en hoe jouw ideale eilandverblijf eruitziet. Ons team bevestigt de beschikbaarheid en stemt de details af.', startReservation:'Start je reservering', noPayment:'Geen betaling nodig · Aanvraag via WhatsApp of e-mail',
    bookingEyebrow:'Reserveringsaanvraag', bookingTitle:'Laten we je eilandverblijf plannen.', bookingBody:'Deel enkele gegevens en kies hoe je de aanvraag wilt versturen. Het team antwoordt met beschikbaarheid en een offerte op maat.', name:'Naam en achternaam', arrival:'Aankomst', departure:'Vertrek', adults:'Volwassenen', children:'Kinderen (4–12)', addStay:'Voeg toe aan je verblijf', boatTransfer:'Retourtransfer per boot', anythingElse:'Nog iets anders?', messagePlaceholder:'Viering, dieetwensen, kamervoorkeur…', summaryPrompt:'Kies je data om de samenvatting te zien.', sendWhatsApp:'Verstuur via WhatsApp', sendEmail:'Verstuur per e-mail', errorDate:'Kies een vertrekdatum na de aankomst.', night:'nacht', nights:'nachten', adultWord:'volwassene', adultsWord:'volwassenen', childWord:'kind', childrenWord:'kinderen', reservations:'Reserveringen', follow:'Volg ons'
  },
  da: {
    navStay:'Ophold', navExperiences:'Oplevelser', navGallery:'Galleri', navJourney:'Sådan kommer du hertil', planStay:'Planlæg dit ophold',
    location:'Inhaca Island · Mozambique', heroTitle:'Byt byen ud<br>med ø-tid.', heroLede:'Ti fredelige værelser, morgenmad hver dag og Det Indiske Ocean lige udenfor — kun 60 minutter med speedbåd fra Maputo.', checkDates:'Se datoer', discover:'Oplev Villa Martins', guestRooms:'gæsteværelser', fromMaputo:'fra Maputo', daily:'Daglig', breakfastIncluded:'morgenmad inkluderet',
    storyEyebrow:'Øen i dit tempo', storyTitle:'En roligere form for luksus.', storyLead:'Her er luksus friheden til at sænke tempoet: en varm velkomst, en barfodet tur til stranden og ingen andre steder, du skal være.', storyBody:'Villa Martins er skabt som et komfortabelt og autentisk ø-tilflugtssted. Rummene er afslappede og indbydende, tæt på naturen og det smukke marineområde.', welcomeHome:'Velkommen til dit ø-hjem',
    stayEyebrow:'Bo godt', stayTitle:'Enkelt. Behageligt.<br>Skabt til at koble af.', stayBody:'Ti gennemtænkte værelser åbner mod tropiske haver og poolen. Daglig morgenmad er inkluderet, og restauranten serverer øvrige måltider.', villaKicker:'Villaen', villaTitle:'Alt er tæt på, intet haster.', poolGarden:'Pool og have', restaurant:'Restaurant på stedet', poolsideKicker:'Dage ved poolen', poolsideTitle:'Køligt vand, varm sol.', quote:'“Et fredeligt stykke paradis.”',
    experiencesEyebrow:'Ude på øen', experiencesTitle:'Følg tidevandet.', experiencesBody:'Tilbring dagen i klart vand, opdag stille strande eller se øen fra oven. Vi hjælper med at forme dagen omkring dig.', snorkelling:'Snorkling', snorkellingBody:'Oplev farverigt havliv i klart, varmt vand.', beachWalks:'Strandture', beachWalksBody:'Barfodede ture og stille øjeblikke ved kysten.', islandTour:'Ø-tur', islandTourBody:'Udforsk Inhaca og gå op til det historiske fyrtårn.', fishing:'Havfiskeri', fishingShort:'Fiskeri', fishingBody:'Tag ud i Det Indiske Oceans rige farvande.', whales:'Hvalsafari', whalesBody:'Oplev pukkelhvalernes sæsonvandring.',
    galleryEyebrow:'Et glimt af ø-livet', galleryTitle:'Ville du ønske, du var her?', galleryBody:'Rolige morgener, blåt vand og middage i solnedgangen. Tryk på et foto for at se nærmere.', galleryCount:'Komplet galleri · 27 billeder',
    journeyEyebrow:'Rejsen er en del af oplevelsen', journeyTitle:'Fra Maputo til ø-ro på 60 minutter.', journeyBody:'Vores speedbåd forbinder Maputo og Inhaca Island og gør ankomsten til opholdets første minde.', routeMeet:'Mød os i Maputo', routeMeetBody:'Vi bekræfter detaljerne for afgang.', routeCross:'Kryds bugten', routeCrossBody:'En naturskøn tur på 60 minutter.', routeArrive:'Ankomst til Inhaca', routeArriveBody:'Velkommen til Villa Martins.', viewMap:'Se på Google Maps',
    ctaEyebrow:'Dine ø-datoer', ctaTitle:'Når du er klar.', ctaBody:'Fortæl os, hvornår du vil rejse, og hvordan dit perfekte ø-ophold ser ud. Vores team bekræfter ledighed og tilpasser detaljerne.', startReservation:'Start reservationen', noPayment:'Ingen betaling · Forespørg via WhatsApp eller e-mail',
    bookingEyebrow:'Reservationsforespørgsel', bookingTitle:'Lad os planlægge dit ø-ophold.', bookingBody:'Del nogle få oplysninger, og vælg hvordan forespørgslen sendes. Teamet svarer med ledighed og et tilpasset tilbud.', name:'Navn og efternavn', arrival:'Ankomst', departure:'Afrejse', adults:'Voksne', children:'Børn (4–12)', addStay:'Føj til opholdet', boatTransfer:'Returtransfer med båd', anythingElse:'Noget andet?', messagePlaceholder:'Fejring, kostbehov, værelsesønske…', summaryPrompt:'Vælg dine datoer for at se oversigten.', sendWhatsApp:'Send via WhatsApp', sendEmail:'Send via e-mail', errorDate:'Vælg en afrejsedato efter ankomsten.', night:'nat', nights:'nætter', adultWord:'voksen', adultsWord:'voksne', childWord:'barn', childrenWord:'børn', reservations:'Reservationer', follow:'Følg os'
  },
  gd: {
    navStay:'Fuirich', navExperiences:'Eòlasan', navGallery:'Gailearaidh', navJourney:'Mar a ruigeas tu', planStay:'Dealbhaich do thuras',
    location:'Eilean Inhaca · Mòsaimbic', heroTitle:'Fàg am baile<br>airson àm an eilein.', heroLede:'Deich seòmraichean sìtheil, bracaist gach madainn agus an Cuan Innseanach aig an doras — dìreach 60 mionaid ann am bàta-luath à Maputo.', checkDates:'Thoir sùil air cinn-là', discover:'Faigh eòlas air Villa Martins', guestRooms:'seòmraichean aoighean', fromMaputo:'à Maputo', daily:'Gach latha', breakfastIncluded:'bracaist air a ghabhail a-steach',
    storyEyebrow:'An t-eilean, air do shocair', storyTitle:'Sòghalachd nas sìtheile.', storyLead:'An seo, is e sòghalachd an saorsa slaodadh sìos: fàilte bhlàth, coiseachd cas-rùisgte chun na tràghad agus gun àite eile far am feum thu a bhith.', storyBody:'Chaidh Villa Martins a chruthachadh mar thearmann eileanach cofhurtail agus fìor. Tha na h-àiteachan socair agus fàilteachail, faisg air nàdar agus tèarmann na mara.', welcomeHome:'Fàilte don dachaigh eileanach agad',
    stayEyebrow:'Fuirich gu math', stayTitle:'Sìmplidh. Cofhurtail.<br>Air a dhèanamh airson fois.', stayBody:'Tha deich seòmraichean a’ fosgladh gu gàrraidhean tropaigeach agus an amar-snàmh. Tha bracaist làitheil ann agus taigh-bìdh airson biadh eile.', villaKicker:'A’ Villa', villaTitle:'A h-uile càil faisg, gun chabhaig.', poolGarden:'Amar agus gàrradh', restaurant:'Taigh-bìdh air an làraich', poolsideKicker:'Làithean ri taobh na linne', poolsideTitle:'Uisge fionnar, grian bhlàth.', quote:'“Pìos sìtheil de phàrras.”',
    experiencesEyebrow:'A-muigh air an eilean', experiencesTitle:'Lean an làn.', experiencesBody:'Cuir seachad an latha ann an uisge soilleir, lorg tràighean sàmhach no faic an t-eilean bho shuas. Cuidichidh sinn thu leis an latha.', snorkelling:'Snorcladh', snorkellingBody:'Faic beatha na mara ann an uisge blàth, soilleir.', beachWalks:'Cuairtean tràghad', beachWalksBody:'Coiseachd cas-rùisgte agus amannan sàmhach ri taobh na mara.', islandTour:'Turas eilein', islandTourBody:'Rannsaich Inhaca agus streap chun taigh-sholais eachdraidheil.', fishing:'Iasgach mara', fishingShort:'Iasgach', fishingBody:'Rach a-mach gu uisgeachan beairteach a’ Chuain Innseanaich.', whales:'Coimhead nam mucan-mara', whalesBody:'Faic imrich ràitheil nam mucan-mara crothach.',
    galleryEyebrow:'Sealladh air beatha an eilein', galleryTitle:'Nach bu toil leat a bhith an seo?', galleryBody:'Madainnean slaodach, uisge gorm agus dìnnearan aig dol fodha na grèine. Tap air dealbh airson fhaicinn nas motha.', galleryCount:'Gailearaidh slàn · 27 dealbhan',
    journeyEyebrow:'Tha an turas na phàirt dheth', journeyTitle:'Bho Maputo gu sìth an eilein ann an 60 mionaid.', journeyBody:'Tha am bàta-luath againn a’ ceangal Maputo agus Inhaca, agus tha an ruighinn na chiad chuimhne den teicheadh.', routeMeet:'Coinnich ann am Maputo', routeMeetBody:'Dearbhaidh sinn fiosrachadh an turais.', routeCross:'Tarsainn a’ bhàigh', routeCrossBody:'Turas seallaidh 60 mionaid.', routeArrive:'Ruig Inhaca', routeArriveBody:'Fàilte gu Villa Martins.', viewMap:'Faic air Google Maps',
    ctaEyebrow:'Na cinn-là eileanach agad', ctaTitle:'Nuair a bhios tu deiseil.', ctaBody:'Innis dhuinn cuin a tha thu airson siubhal agus cò ris a tha an turas foirfe coltach. Dearbhaidh an sgioba againn na tha ri fhaighinn.', startReservation:'Tòisich air glèidheadh', noPayment:'Gun phàigheadh · Iarrtas tro WhatsApp no post-d',
    bookingEyebrow:'Iarrtas glèidhidh', bookingTitle:'Dealbhaichidh sinn do thuras eileanach.', bookingBody:'Roinn beagan fiosrachaidh agus tagh mar a chuireas tu an t-iarrtas. Freagraidh an sgioba le cothrom agus prìs phearsanta.', name:'Ainm agus sloinneadh', arrival:'Ruighinn', departure:'Fàgail', adults:'Inbhich', children:'Clann (4–12)', addStay:'Cuir ris an turas', boatTransfer:'Bàta air ais is air adhart', anythingElse:'Rud sam bith eile?', messagePlaceholder:'Comharrachadh, daithead, roghainn seòmair…', summaryPrompt:'Tagh cinn-là airson geàrr-chunntas fhaicinn.', sendWhatsApp:'Cuir tro WhatsApp', sendEmail:'Cuir air post-d', errorDate:'Tagh ceann-latha fàgail às dèidh ruighinn.', night:'oidhche', nights:'oidhcheannan', adultWord:'inbheach', adultsWord:'inbhich', childWord:'pàiste', childrenWord:'clann', reservations:'Glèidheadh', follow:'Lean sinn'
  },
  zh: {
    navStay:'住宿', navExperiences:'体验', navGallery:'相册', navJourney:'交通', planStay:'规划住宿',
    location:'伊尼亚卡岛 · 莫桑比克', heroTitle:'告别城市，<br>进入海岛时光。', heroLede:'十间宁静客房、每日早餐，以及近在咫尺的印度洋——从马普托乘快艇仅需60分钟。', checkDates:'查询日期', discover:'探索 Villa Martins', guestRooms:'间客房', fromMaputo:'从马普托出发', daily:'每日', breakfastIncluded:'含早餐',
    storyEyebrow:'按自己的节奏享受海岛', storyTitle:'一种更宁静的奢华。', storyLead:'在这里，奢华意味着可以慢下来：温暖的欢迎、赤脚走向海岸，以及无需赶往任何地方。', storyBody:'Villa Martins 是一处舒适而真实的海岛度假之所。空间轻松宜人，与棕榈、海风和附近壮丽的海洋保护区自然相连。', welcomeHome:'欢迎来到您的海岛之家',
    stayEyebrow:'舒适入住', stayTitle:'简单。舒适。<br>为放松而生。', stayBody:'十间精心设计的客房面向热带花园和泳池。住宿包含每日早餐，餐厅亦供应其他餐点。', villaKicker:'别墅', villaTitle:'一切都很近，无需匆忙。', poolGarden:'泳池与花园', restaurant:'店内餐厅', poolsideKicker:'泳池时光', poolsideTitle:'清凉水面，温暖阳光。', quote:'“一片宁静的天堂。”',
    experiencesEyebrow:'探索海岛', experiencesTitle:'随潮而行。', experiencesBody:'在清澈海水中度过一天，发现安静海滩，或从高处俯瞰小岛。我们可按您的节奏安排行程。', snorkelling:'浮潜', snorkellingBody:'在清澈温暖的海水中发现缤纷海洋生物。', beachWalks:'海滩漫步', beachWalksBody:'赤脚漫步，享受海岸边的宁静时刻。', islandTour:'环岛游', islandTourBody:'探索伊尼亚卡并登上历史悠久的灯塔。', fishing:'海钓', fishingShort:'钓鱼', fishingBody:'驶向印度洋丰富的海域。', whales:'观鲸', whalesBody:'在季节性迁徙期间观看座头鲸。',
    galleryEyebrow:'海岛生活一瞥', galleryTitle:'希望您也在这里吗？', galleryBody:'悠闲清晨、湛蓝海水和落日晚餐。点击照片即可放大查看。', galleryCount:'完整相册 · 27 张照片',
    journeyEyebrow:'旅程也是体验的一部分', journeyTitle:'从马普托到海岛宁静，只需60分钟。', journeyBody:'我们的快艇连接马普托与伊尼亚卡岛，让抵达本身成为假期的第一个难忘时刻。', routeMeet:'在马普托集合', routeMeetBody:'我们会确认您的出发详情。', routeCross:'穿越海湾', routeCrossBody:'60分钟的观景快艇旅程。', routeArrive:'抵达伊尼亚卡', routeArriveBody:'欢迎来到 Villa Martins。', viewMap:'在 Google 地图查看',
    ctaEyebrow:'您的海岛日期', ctaTitle:'随时准备出发。', ctaBody:'告诉我们您的出行日期和理想住宿方式。团队将确认房态并为您定制细节。', startReservation:'开始预订', noPayment:'无需付款 · 通过 WhatsApp 或电子邮件咨询',
    bookingEyebrow:'预订申请', bookingTitle:'让我们规划您的海岛住宿。', bookingBody:'提供一些信息并选择发送方式。Villa Martins 团队将回复房态和个性化报价。', name:'姓名', arrival:'入住日期', departure:'离店日期', adults:'成人', children:'儿童（4–12岁）', addStay:'添加体验', boatTransfer:'往返快艇接送', anythingElse:'还有其他需求吗？', messagePlaceholder:'庆祝活动、饮食需求、房型偏好……', summaryPrompt:'选择日期后查看住宿摘要。', sendWhatsApp:'通过 WhatsApp 发送', sendEmail:'通过电子邮件发送', errorDate:'离店日期必须晚于入住日期。', night:'晚', nights:'晚', adultWord:'位成人', adultsWord:'位成人', childWord:'名儿童', childrenWord:'名儿童', reservations:'预订', follow:'关注我们'
  }
};
